// Copy for the Previous Deployments page (Figma EN 133:1282 / AR 161:914).

export default {
  en: {
    hero: {
      eyebrow: 'Track record',
      title: 'Previous deployments',
      highlight: ['deployments'],
      description:
        'A selection of Saudi employers we have recruited for — across hospitality, food production, construction, manufacturing, facilities and security.',
      cta: 'Start your deployment',
    },
    stats: [
      { value: '18+', label: 'Years in overseas recruitment' },
      { value: '6', label: 'Offices across the Philippines' },
      { value: '45–60', label: 'Days from job order to deployment' },
      { value: '2029', label: 'DMW license valid through', static: true },
    ],
    recent: {
      eyebrow: 'Recent principals',
      title: 'Recent deployments',
      filterLabel: 'Filter deployments by sector',
      filters: [
        { id: 'all', label: 'All' },
        { id: 'hospitality', label: 'Hospitality' },
        { id: 'construction', label: 'Construction' },
        { id: 'manufacturing', label: 'Manufacturing' },
        { id: 'security', label: 'Security' },
      ],
      empty: 'No featured deployment in this sector yet — see the full list of job orders below.',
      cards: [
        {
          id: 'em-sherif',
          sector: 'hospitality',
          sectorLabel: 'Hospitality',
          title: 'Waitresses & commis for Em Sherif Sea Cafe',
          city: 'Riyadh',
          roles: 'Waitress · Commi',
          image: 'aboutHero',
          alt: 'Riyadh skyline with Kingdom Centre — Filipino workers deployed to Saudi Arabia',
        },
        {
          id: 'githa',
          sector: 'food',
          sectorLabel: 'Food production',
          title: 'Chef cooks for Githa Smart Food Company',
          city: 'Saudi Arabia',
          roles: 'Chef cook',
          image: 'citySaudi',
          alt: 'Saudi city towers at sunset — manpower deployment for KSA employers',
        },
        {
          id: 'aswar',
          sector: 'manufacturing',
          sectorLabel: 'Manufacturing',
          title: 'Machine operators for Aswar Al Watan Plastic Factory',
          city: 'Saudi Arabia',
          roles: 'CNC lathe · Lamination operators',
          image: 'deploy4',
          alt: 'Office tower — manufacturing and industrial manpower recruitment for Saudi Arabia',
        },
        {
          id: 'edama',
          sector: 'security',
          sectorLabel: 'Security',
          title: 'CCTV operators for Edama Properties Operation',
          city: 'Dammam',
          roles: 'CCTV operator',
          image: 'cityPhilippines',
          alt: 'Gulf city skyline — security and facilities staff recruitment for Saudi Arabia',
        },
      ],
    },
    log: {
      eyebrow: 'Recent job orders',
      title: 'Who we recruit for',
      note: 'Selected principals in Saudi Arabia',
      columns: { employer: 'Employer', sector: 'Sector', location: 'Location', roles: 'Roles recruited' },
      rows: [
        {
          employer: 'Gulf Alstone Co. Ltd.',
          sector: 'construction',
          sectorLabel: 'Construction',
          location: 'Saudi Arabia',
          roles: 'Batching plant operator, industrial electrician, mason / tile setter, TIG/MIG welder',
        },
        { employer: 'Em Sherif Sea Cafe', sector: 'hospitality', sectorLabel: 'Hospitality', location: 'Riyadh', roles: 'Waitress, commi' },
        { employer: 'Githa Smart Food Company', sector: 'food', sectorLabel: 'Food production', location: 'Saudi Arabia', roles: 'Chef cook' },
        {
          employer: 'Aswar Al Watan Plastic Factory',
          sector: 'manufacturing',
          sectorLabel: 'Manufacturing',
          location: 'Saudi Arabia',
          roles: 'CNC lathe machine operator, lamination machine operator',
        },
        { employer: 'Areen Operations and Maintenance', sector: 'facilities', sectorLabel: 'Facilities', location: 'Saudi Arabia', roles: 'Cleaner' },
        { employer: 'Edama Properties Operation', sector: 'security', sectorLabel: 'Security', location: 'Dammam', roles: 'CCTV operator' },
      ],
    },
    prep: {
      eyebrow: 'Before deployment',
      title: 'Every worker, fully prepared',
      cards: [
        {
          icon: 'award',
          title: 'Skills tested',
          text: 'Trade tests and assessments through accredited skills testing and training centres before selection.',
        },
        {
          icon: 'file',
          title: 'Complete documentation',
          text: 'Passport, NBI clearance, medicals and DMW processing handled for every worker we deploy.',
        },
        {
          icon: 'plane',
          title: 'Ready to work',
          text: 'Pre-departure orientation so every worker arrives prepared for life and work in Saudi Arabia.',
        },
      ],
    },
    cta: {
      heading: 'Want results like these?',
      subtext: "Tell us about your next project and we'll build a deployment plan around it.",
      primary: 'Request a shortlist',
      secondary: 'Talk to our team',
    },
  },

  ar: {
    hero: {
      eyebrow: 'سجل إنجازاتنا',
      title: 'مشاريع الاستقدام السابقة',
      highlight: ['مشاريع', 'الاستقدام'],
      description:
        'نخبة من أصحاب العمل في المملكة الذين استقدمنا لهم العمالة — في الضيافة وإنتاج الأغذية والبناء والتصنيع والمرافق والأمن.',
      cta: 'ابدأ طلب الاستقدام',
    },
    stats: [
      { value: '18+', label: 'عامًا في الاستقدام الخارجي' },
      { value: '6', label: 'مكاتب في أنحاء الفلبين' },
      { value: '45–60', label: 'يومًا من طلب الاستقدام حتى السفر' },
      { value: '2029', label: 'ترخيص DMW ساري حتى', static: true },
    ],
    recent: {
      eyebrow: 'أحدث العملاء',
      title: 'أحدث مشاريع الاستقدام',
      filterLabel: 'تصفية المشاريع حسب القطاع',
      filters: [
        { id: 'all', label: 'الكل' },
        { id: 'hospitality', label: 'الضيافة' },
        { id: 'construction', label: 'البناء' },
        { id: 'manufacturing', label: 'التصنيع' },
        { id: 'security', label: 'الأمن' },
      ],
      empty: 'لا يوجد مشروع مميز في هذا القطاع حاليًا — اطّلع على قائمة طلبات الاستقدام أدناه.',
      cards: [
        {
          id: 'em-sherif',
          sector: 'hospitality',
          sectorLabel: 'الضيافة',
          title: 'نادلات ومساعدو طهاة لمطعم إم شريف سي كافيه',
          city: 'الرياض',
          roles: 'نادلة · مساعد طاهٍ',
          image: 'aboutHero',
          alt: 'أفق الرياض وبرج المملكة — عمالة فلبينية مستقدمة للسعودية',
        },
        {
          id: 'githa',
          sector: 'food',
          sectorLabel: 'إنتاج الأغذية',
          title: 'طهاة لشركة غذاء الذكية',
          city: 'المملكة العربية السعودية',
          roles: 'طاهٍ',
          image: 'citySaudi',
          alt: 'أبراج مدينة سعودية عند الغروب — توريد العمالة لأصحاب العمل في المملكة',
        },
        {
          id: 'aswar',
          sector: 'manufacturing',
          sectorLabel: 'التصنيع',
          title: 'مشغلو آلات لمصنع أسوار الوطن للبلاستيك',
          city: 'المملكة العربية السعودية',
          roles: 'مخارط CNC · مشغلو آلات التغليف',
          image: 'deploy4',
          alt: 'برج مكاتب — استقدام عمالة المصانع والصناعة للسعودية',
        },
        {
          id: 'edama',
          sector: 'security',
          sectorLabel: 'الأمن',
          title: 'مشغلو كاميرات مراقبة لشركة إدامة لتشغيل العقارات',
          city: 'الدمام',
          roles: 'مشغل كاميرات مراقبة',
          image: 'cityPhilippines',
          alt: 'أفق مدينة خليجية — استقدام عمالة الأمن والمرافق للسعودية',
        },
      ],
    },
    log: {
      eyebrow: 'أحدث طلبات الاستقدام',
      title: 'لمن نستقدم',
      note: 'نخبة من عملائنا في المملكة',
      columns: { employer: 'صاحب العمل', sector: 'القطاع', location: 'الموقع', roles: 'الوظائف المستقدمة' },
      rows: [
        {
          employer: 'شركة جلف ألستون المحدودة',
          sector: 'construction',
          sectorLabel: 'البناء',
          location: 'المملكة العربية السعودية',
          roles: 'مشغل محطة خرسانة، كهربائي صناعي، بنّاء / مبلّط، لحام TIG/MIG',
        },
        { employer: 'إم شريف سي كافيه', sector: 'hospitality', sectorLabel: 'الضيافة', location: 'الرياض', roles: 'نادلة، مساعد طاهٍ' },
        { employer: 'شركة غذاء الذكية', sector: 'food', sectorLabel: 'إنتاج الأغذية', location: 'المملكة العربية السعودية', roles: 'طاهٍ' },
        {
          employer: 'مصنع أسوار الوطن للبلاستيك',
          sector: 'manufacturing',
          sectorLabel: 'التصنيع',
          location: 'المملكة العربية السعودية',
          roles: 'مشغل مخرطة CNC، مشغل آلة تغليف',
        },
        { employer: 'عرين للتشغيل والصيانة', sector: 'facilities', sectorLabel: 'المرافق', location: 'المملكة العربية السعودية', roles: 'عامل نظافة' },
        { employer: 'إدامة لتشغيل العقارات', sector: 'security', sectorLabel: 'الأمن', location: 'الدمام', roles: 'مشغل كاميرات مراقبة' },
      ],
    },
    prep: {
      eyebrow: 'قبل السفر',
      title: 'كل عامل، جاهز تمامًا',
      cards: [
        { icon: 'award', title: 'مهارات مختبرة', text: 'اختبارات وتقييمات مهنية في مراكز اختبار وتدريب معتمدة قبل الاختيار.' },
        {
          icon: 'file',
          title: 'مستندات مكتملة',
          text: 'نتولى جواز السفر وشهادة حسن السيرة (NBI) والفحوصات الطبية وإجراءات DMW لكل عامل نستقدمه.',
        },
        { icon: 'plane', title: 'جاهز للعمل', text: 'توجيه قبل السفر ليصل كل عامل مستعدًا للحياة والعمل في المملكة العربية السعودية.' },
      ],
    },
    cta: {
      heading: 'هل تريد نتائج مماثلة؟',
      subtext: 'أخبرنا عن مشروعك القادم وسنضع خطة استقدام تناسبه.',
      primary: 'اطلب قائمة مرشحين',
      secondary: 'تحدث إلى فريقنا',
    },
  },
}
