// Copy for the Home page (Figma: EN frame 126:13, AR frame 161:69).
import { LICENSE_NO } from './common.js'

const MAPS_URL = 'https://www.google.com/maps/search/?api=1&query=Merchant+Center+Building+Padre+Faura+St+Ermita+Manila'
const PHONES = '(02) 5302-1952 to 54 · (02) 8522-4174'

export default {
  en: {
    hero: {
      eyebrow: `DMW License No. ${LICENSE_NO}`,
      title: 'Filipino talent for the Kingdom’s growth',
      highlight: ['Filipino', 'talent'],
      body: 'Gulf Horizon International Services, Inc. is a DMW-licensed agency in Manila, deploying skilled Filipino professionals and workers to employers across Saudi Arabia — in every skill and job category.',
      cta: 'Send a job order',
      proofTitle: '18+ years of overseas placements',
      proofSub: 'Head office in Manila + 5 regional branches',
      avatarsAlt: 'Logos of employers we recruit for',
      photoAlt: 'Two Filipino professionals in business attire in front of a Gulf city skyline at sunset',
      mediaCta: 'View manpower categories',
      statValue: '45–60 days',
      statLabel: 'From job order to deployment',
    },
    statsLabel: 'Key figures',
    stats: [
      { value: '18+', label: 'Years in overseas recruitment' },
      { value: '6', label: 'Offices across the Philippines' },
      { value: '45–60', label: 'Days from job order to deployment' },
      { value: '2029', label: 'DMW license valid through' },
    ],
    values: {
      eyebrow: 'THE GULF HORIZON DIFFERENCE',
      title: 'Why employers choose us',
      description: 'Our mission is simple: build a lasting reputation for integrity and reliability, and meet even the most demanding manpower requests of our Saudi principals.',
      items: [
        { title: 'Direct Sourcing', body: 'Filipino talent recruited through our Manila head office and branches in Davao, Iloilo, Pangasinan, Bacolod and Cagayan de Oro.' },
        { title: 'Integrity & Reliability', body: 'Clear processes and honest timelines — the reputation we have built over more than 18 years of overseas recruitment.' },
        { title: 'Skills-Tested Workers', body: 'Every candidate is trade-tested through accredited skills testing and training centres before selection.' },
        { title: 'Licensed & Compliant', body: 'Licensed by the Department of Migrant Workers (formerly POEA) and aligned with Saudi requirements.' },
      ],
    },
    categories: {
      eyebrow: 'WHAT WE SUPPLY',
      title: 'Manpower for every part of your operation',
      description: 'Licensed to recruit land-based workers across all skills and job categories — these are the roles Saudi employers ask us for most.',
      feature: {
        tag: 'CATEGORY 01 · MOST REQUESTED',
        title: 'Skilled Trades & Manufacturing',
        body: 'Trade-tested at accredited centres before selection — ready for construction sites, factories and plants across the Kingdom.',
        roles: [
          'TIG / MIG welders',
          'Industrial electricians',
          'Masons & tile setters',
          'Batching plant operators',
          'CNC lathe operators',
          'Lamination & flexo operators',
          'CCTV operators',
        ],
      },
      link: 'Request this category',
      cards: [
        { tag: 'CATEGORY 02', title: 'Hospitality & F&B', roles: 'Waitresses · Commis · Chef cooks · Baristas · Housekeeping', alt: 'Grand hotel lobby with crystal chandeliers' },
        { tag: 'CATEGORY 03', title: 'Healthcare & Care', roles: 'Staff nurses · Caregivers · Medical aides', alt: 'Filipino nurse caring for an elderly patient' },
        { tag: 'CATEGORY 04', title: 'Domestic & Household', roles: 'Housekeepers · Nannies · Family cooks', alt: 'Smiling Filipino housekeeper in uniform' },
        { tag: 'CATEGORY 05', title: 'Drivers & Logistics', roles: 'Family drivers · Heavy-vehicle drivers · Warehouse staff', alt: 'Luxury car in front of the Riyadh skyline' },
      ],
    },
    process: {
      eyebrow: 'HOW IT WORKS',
      title: 'From job order to arrival in 45–60 days',
      description: 'One accountable team handles every stage — so you deal with a single point of contact, from your first request to your workers’ first day.',
      steps: [
        { title: 'Job order', body: 'Share the roles, headcount, skills and timeline you need.' },
        { title: 'Sourcing & screening', body: 'We source through our Manila office and five regional branches.' },
        { title: 'Testing & interviews', body: 'Trade tests at accredited centres, then interviews with your team.' },
        { title: 'Documents & visa', body: 'DMW processing, medicals, visa and contract verification.' },
        { title: 'Deployment', body: 'Pre-departure orientation, ticketing and arrival confirmation.' },
      ],
    },
    clients: {
      eyebrow: 'TRUSTED ACROSS THE GULF',
      title: 'Employers who rely on us',
      description: 'A selection of the 77+ hospitals, manufacturers, hotels and business groups we have recruited for across Saudi Arabia and the Gulf.',
      items: [
        { name: 'King Khaled Eye Specialist Hospital', place: 'Riyadh, KSA' },
        { name: 'Al Othaim Commercial Co.', place: 'Riyadh, KSA' },
        { name: 'Herfy Food Services', place: 'Riyadh, KSA' },
        { name: 'Al Ghurair Group', place: 'Dubai, UAE' },
        { name: 'Radisson SAS Hotel', place: 'Jeddah, KSA' },
        { name: 'Tabuk Cement', place: 'Tabuk, KSA' },
        { name: 'Al-Mojil Co.', place: 'Dammam, KSA' },
        { name: 'University Hospital of Sharjah', place: 'Sharjah, UAE' },
      ],
      link: 'See our full client list',
      logoAlt: 'logo',
    },
    visit: {
      eyebrow: 'VISIT US',
      title: 'Our office in the heart of Ermita',
      body: 'Our Manila head office is open for employer consultations, document handovers and candidate interviews by appointment.',
      details: [
        { label: 'HEAD OFFICE', value: '509 Merchant Center Bldg., 3rd Floor, Padre Faura St. cor. Mabini St., Ermita, Manila' },
        { label: 'TELEPHONE', value: PHONES, ltr: true },
        { label: 'REGIONAL BRANCHES', value: 'Davao · Iloilo · Pangasinan · Bacolod · Cagayan de Oro' },
      ],
      cta: 'Open in Maps',
      mapsUrl: MAPS_URL,
      map: {
        label: 'Stylised map of the Gulf Horizon head office in Ermita, Manila',
        streetA: 'PADRE FAURA ST.',
        streetB: 'MABINI ST.',
        pinTitle: 'Gulf Horizon International Services',
        pinSub: '3/F Merchant Center Bldg., Ermita',
        hours: 'Consultations by appointment',
      },
    },
  },
  ar: {
    hero: {
      eyebrow: `رقم ترخيص DMW: ${LICENSE_NO}`,
      title: 'كفاءات فلبينية لنمو المملكة',
      highlight: ['كفاءات', 'فلبينية'],
      body: 'أفق الخليج للخدمات العالمية وكالة استقدام مرخّصة من DMW مقرها مانيلا، تستقدم المهنيين والعمال الفلبينيين المهرة لأصحاب العمل في جميع أنحاء المملكة العربية السعودية — في جميع المهارات والتخصصات.',
      cta: 'أرسل طلب استقدام',
      proofTitle: 'أكثر من 18 عامًا في التوظيف الخارجي',
      proofSub: 'مكتب رئيسي في مانيلا و5 فروع إقليمية',
      avatarsAlt: 'شعارات أصحاب عمل نستقدم لهم',
      photoAlt: 'مهنيان فلبينيان بزي رسمي أمام أفق مدينة خليجية عند الغروب',
      mediaCta: 'استعرض فئات العمالة',
      statValue: '45–60 يومًا',
      statLabel: 'من طلب الاستقدام حتى السفر',
    },
    statsLabel: 'أرقام رئيسية',
    stats: [
      { value: '18+', label: 'عامًا في الاستقدام الخارجي' },
      { value: '6', label: 'مكاتب في أنحاء الفلبين' },
      { value: '45–60', label: 'يومًا من طلب الاستقدام حتى السفر' },
      { value: '2029', label: 'ترخيص DMW ساري حتى' },
    ],
    values: {
      eyebrow: 'ما يميز أفق الخليج',
      title: 'لماذا يختارنا أصحاب العمل',
      description: 'رسالتنا واضحة: بناء سمعة راسخة في النزاهة والموثوقية، وتلبية أكثر طلبات العمالة تطلبًا لعملائنا في المملكة.',
      items: [
        { title: 'استقطاب مباشر', body: 'كفاءات فلبينية نستقطبها عبر مكتبنا الرئيسي في مانيلا وفروعنا في دافاو وإيلويلو وبانغاسينان وباكولود وكاغايان دي أورو.' },
        { title: 'النزاهة والموثوقية', body: 'إجراءات واضحة وجداول زمنية صادقة — سمعة بنيناها على مدى أكثر من 18 عامًا في الاستقدام الخارجي.' },
        { title: 'عمالة مختبرة المهارات', body: 'يخضع كل مرشح لاختبار مهني في مراكز اختبار وتدريب معتمدة قبل الاختيار.' },
        { title: 'مرخّصون وملتزمون', body: 'مرخّصون من إدارة العمال المهاجرين (POEA سابقًا) وملتزمون بالمتطلبات السعودية.' },
      ],
    },
    categories: {
      eyebrow: 'ما نوفّره',
      title: 'عمالة لكل جزء من أعمالك',
      description: 'مرخّصون لاستقدام العمالة في جميع المهارات والتخصصات — وهذه أكثر الوظائف التي يطلبها أصحاب العمل في المملكة.',
      feature: {
        tag: 'الفئة 01 · الأكثر طلبًا',
        title: 'الحرف الماهرة والتصنيع',
        body: 'مختبرون مهنيًا في مراكز معتمدة قبل الاختيار — جاهزون لمواقع البناء والمصانع والمنشآت في أنحاء المملكة.',
        roles: [
          'لحامو TIG / MIG',
          'كهربائيون صناعيون',
          'بنّاؤون ومبلّطون',
          'مشغلو محطات الخرسانة',
          'مشغلو مخارط CNC',
          'مشغلو آلات التغليف والطباعة',
          'مشغلو كاميرات المراقبة',
        ],
      },
      link: 'اطلب هذه الفئة',
      cards: [
        { tag: 'الفئة 02', title: 'الضيافة والأغذية والمشروبات', roles: 'نادلات · مساعدو طهاة · طهاة · باريستا · تدبير منزلي', alt: 'ردهة فندق فاخر بثريات كريستالية' },
        { tag: 'الفئة 03', title: 'الرعاية الصحية والتمريض', roles: 'ممرضون · مقدمو رعاية · مساعدون طبيون', alt: 'ممرضة فلبينية تعتني بمريض مسن' },
        { tag: 'الفئة 04', title: 'العمالة المنزلية', roles: 'عاملات منزليات · مربيات · طهاة منازل', alt: 'عاملة منزلية فلبينية مبتسمة بالزي الرسمي' },
        { tag: 'الفئة 05', title: 'السائقون والخدمات اللوجستية', roles: 'سائقو عائلات · سائقو معدات ثقيلة · عمال مستودعات', alt: 'سيارة فاخرة أمام أفق مدينة الرياض' },
      ],
    },
    process: {
      eyebrow: 'كيف نعمل',
      title: 'من طلب الاستقدام حتى الوصول خلال 45–60 يومًا',
      description: 'فريق واحد مسؤول يتولى كل مرحلة — لتتعامل مع جهة تواصل واحدة من طلبك الأول حتى أول يوم عمل لعمالك.',
      steps: [
        { title: 'طلب الاستقدام', body: 'حدّد الوظائف والأعداد والمهارات والجدول الزمني المطلوب.' },
        { title: 'الاستقطاب والفرز', body: 'نستقطب المرشحين عبر مكتبنا في مانيلا وفروعنا الإقليمية الخمسة.' },
        { title: 'الاختبارات والمقابلات', body: 'اختبارات مهنية في مراكز معتمدة، ثم مقابلات مع فريقك.' },
        { title: 'المستندات والتأشيرة', body: 'إجراءات DMW والفحوصات الطبية والتأشيرة وتوثيق العقود.' },
        { title: 'السفر والمباشرة', body: 'التوجيه قبل السفر وحجز التذاكر وتأكيد الوصول.' },
      ],
    },
    clients: {
      eyebrow: 'ثقة في أنحاء الخليج',
      title: 'أصحاب عمل يعتمدون علينا',
      description: 'نخبة من أكثر من 77 مستشفى ومصنعًا وفندقًا ومجموعة أعمال استقدمنا لها العمالة في المملكة ودول الخليج.',
      items: [
        { name: 'مستشفى الملك خالد التخصصي للعيون', place: 'الرياض، السعودية' },
        { name: 'شركة العثيم التجارية', place: 'الرياض، السعودية' },
        { name: 'هرفي للخدمات الغذائية', place: 'الرياض، السعودية' },
        { name: 'مجموعة الغرير', place: 'دبي، الإمارات' },
        { name: 'فندق راديسون ساس', place: 'جدة، السعودية' },
        { name: 'أسمنت تبوك', place: 'تبوك، السعودية' },
        { name: 'شركة المعجل', place: 'الدمام، السعودية' },
        { name: 'مستشفى الجامعة بالشارقة', place: 'الشارقة، الإمارات' },
      ],
      link: 'اطّلع على قائمة عملائنا الكاملة',
      logoAlt: 'شعار',
    },
    visit: {
      eyebrow: 'زورونا',
      title: 'مكتبنا في قلب إرميتا',
      body: 'يستقبل مكتبنا الرئيسي في مانيلا أصحاب العمل للاستشارات وتسليم المستندات ومقابلات المرشحين بموعد مسبق.',
      details: [
        { label: 'المكتب الرئيسي', value: 'مبنى ميرشانت سنتر 509، الطابق الثالث، شارع بادري فاورا تقاطع شارع مابيني، إرميتا، مانيلا' },
        { label: 'الهاتف', value: PHONES, ltr: true },
        { label: 'الفروع الإقليمية', value: 'دافاو · إيلويلو · بانغاسينان · باكولود · كاغايان دي أورو' },
      ],
      cta: 'افتح في الخرائط',
      mapsUrl: MAPS_URL,
      map: {
        label: 'خريطة توضيحية لموقع المكتب الرئيسي لأفق الخليج في إرميتا، مانيلا',
        streetA: 'شارع بادري فاورا',
        streetB: 'شارع مابيني',
        pinTitle: 'أفق الخليج للخدمات العالمية',
        pinSub: 'الطابق 3، مبنى ميرشانت سنتر، إرميتا',
        hours: 'الاستشارات بموعد مسبق',
      },
    },
  },
}
